<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>Library</OutputType>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <Description>Bolter is Kiosk library, featured with both uac &amp; non uac commands</Description>
    <RepositoryUrl>https://github.com/frankfg94/Bolter</RepositoryUrl>
    <RepositoryType>GitHub</RepositoryType>
    <Company>François Gillioen</Company>
    <SignAssembly>false</SignAssembly>
    <CodeAnalysisRuleSet>Bolter.ruleset</CodeAnalysisRuleSet>
    <TargetFramework>net10.0-windows10.0.19041</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile></DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\..\WebLearn\.sonarlint\motivator2\CSharp\SonarLint.xml" Link="SonarLint.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
    <PackageReference Include="System.Management" Version="10.0.12" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="VirtualDesktop" Version="5.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
